- src/components/Modal/ModalSelectAssets.tsx
- src/features/swap/components/SwapForm.tsx
- src/features/swap/components/SwapWidget.tsx
- Remove redundant non-selectable dependencies
- Update form interface
- Move token selection out of form responsibility
> fix: improve token selection behavior in swap form

- package.json
- src/features/deposit/components/DepositWidget.tsx
- src/features/deposit/components/Form/DepositFormNear/index.tsx
- src/features/deposit/services/depositService.ts
- src/features/machines/depositNearMachine.ts
- src/types/deposit.ts
This commit updates the passive deposit function with the following key changes:
- Add Dev description for createDepositNearTransaction function
- Fix transaction object
> chore: update deposit service

- artifacts/defuse_contract_abi.json
It includes newly deployed contract abi.
> chore: update defuse_contract_abi.json

- src/features/machines/queryQuoteMachine.ts
- src/features/machines/swapUIMachine.test.ts
- src/features/machines/swapUIMachine.ts
- src/features/swap/components/SwapUIMachineProvider.tsx
PR mainly addresses an issue of structuring the quote when natively multichain asset is involved.
> refactor(swap): support quoting for natively multichain asset

- src/features/machines/swapIntentMachine.ts
- src/features/machines/swapUIMachine.ts
- src/utils/messageFactory.test.ts
- src/utils/messageFactory.ts
PR reworks the way message to sign is constructed, now it will use real quote to assemble a message.
> feat: use quote for making a message to sign

- src/features/machines/swapIntentMachine.ts
- src/utils/prepareBroadcastRequest.test.ts
- src/utils/prepareBroadcastRequest.ts
PR adds sending a request to Solver-relay API, but it lacks of proper error handling (it will be implemented in follow-up PR).
> feat: add intent publishing

- src/components/Asset/AssetList.tsx
- src/components/Modal/ModalSelectAssets.tsx
- src/features/machines/depositedBalanceMachine.ts
- src/features/machines/swapUIMachine.ts
- src/features/swap/components/SwapForm.tsx
- src/features/swap/components/SwapUIMachineProvider.tsx
- src/features/swap/components/SwapWidget.tsx
- src/types/base.ts
Follow-up of https://github.com/defuse-protocol/defuse-sdk/pull/67
> feat: fetch token balances from list

- src/components/Asset/AssetBalance/index.tsx
- src/components/Asset/AssetList.tsx
- src/components/Block/BlockEvaluatePrice.tsx
- src/components/Block/BlockMultiBalances.tsx
- src/components/Form/FieldComboInput.tsx
- src/components/SelectAssets.tsx
- src/components/WarnBox/index.tsx
- src/features/deposit/components/Form/DepositFormNear/index.tsx
- src/features/swap/components/SwapForm.tsx
- src/utils/balanceTo.ts
- src/utils/format.test.ts
- src/utils/format.ts
- src/utils/token.ts
<details><summary>Screenshot</summary>
<p>
</p>
</details>
> fix: swap UI improvements

- src/config/settings.ts
- src/features/machines/backgroundQuoterMachine.ts
- src/features/machines/queryQuoteMachine.test.ts
- src/features/machines/queryQuoteMachine.ts
- src/features/machines/swapUIMachine.ts
- src/services/solverRelayHttpClient/apis.ts
- src/services/solverRelayHttpClient/runtime.ts
- src/services/solverRelayHttpClient/types.ts
- src/types/quoting.ts
PR make quotes requests send each 500 ms regardless of anything. But only the latest seen quote is taken, all other quotes will be discarded.
> fix: query quote each 500ms

- src/components/IntentCard/SwapIntentCard.tsx
- src/features/swap/components/SwapForm.tsx
It is not final design, but at least it looks prettier and doesn't look broken.
<details><summary>Screenshot</summary>
<p>
</p>
</details>
> fix: update style of swap intent

- src/components/Block/BlockMultiBalances.tsx
- src/components/Form/FieldComboInput.tsx
- src/components/IntentCard/SwapIntentCard.tsx
- src/components/Modal/ModalSelectAssets.tsx
- src/features/machines/queryQuoteMachine.ts
- src/features/machines/swapUIMachine.ts
- src/features/swap/components/SwapForm.tsx
Bunch of UI improvements. One commit - one improvement.
> feat: swap UI improvements

- src/features/deposit/components/DepositForm/index.tsx
- src/features/deposit/components/DepositUIMachineFormSyncProvider.tsx
- src/features/deposit/components/DepositUIMachineProvider.tsx
- src/features/deposit/services/depositService.ts
- src/features/machines/backgroundBalanceActor.ts
- src/features/machines/depositGenerateAddressMachine.ts
- src/features/machines/depositUIMachine.ts
- src/features/withdraw/components/WithdrawForm/index.tsx
- src/hooks/usePoABridge.ts
- src/types/deposit.ts
- src/types/interfaces.ts
- src/utils/adapters.ts
- Add network adapter relation between inner asset chain ID and relay asset chain ID
- Move BlockchainEnum to common interfaces
- Correct extraction of defuseAssetId due to updated asset list
> chore: fix deposit address generation

- src/features/deposit/components/DepositForm/index.tsx
- src/features/deposit/components/DepositUIMachineProvider.tsx
- src/features/deposit/components/Deposits/index.tsx
- src/features/deposit/services/depositService.ts
- src/features/machines/depositNearMachine.ts
- src/features/machines/depositUIMachine.ts
- src/features/machines/getBalanceMachine.ts
- src/services/nearHttpClient/apis.ts
- src/services/nearHttpClient/types.ts
Ensure accurate retrieval of minimum storage deposit for each NEAR NEP-141 token to prevent transaction failures for new users.
> chore: fetch minimum storage deposit for near nep-141 tokens

- src/components/IntentCard/WithdrawIntentCard.tsx
- src/components/Select/Select.tsx
- src/config/settings.ts
- src/features/machines/backgroundQuoterMachine.ts
- src/features/machines/nep141StorageActor.ts
- src/features/machines/swapIntentMachine.ts
- src/features/machines/swapUIMachine.ts
- src/features/machines/withdrawFormReducer.ts
- src/features/machines/withdrawUIMachine.ts
- src/features/swap/components/SwapForm.tsx
- src/features/swap/components/SwapUIMachineProvider.tsx
- src/features/withdraw/WithdrawUIMachineContext.ts
- src/features/withdraw/components/WithdrawForm/index.tsx
- src/features/withdraw/components/WithdrawWidget.tsx
- src/types/quoting.ts
- src/types/withdraw.ts
- src/utils/messageFactory.test.ts
- src/utils/messageFactory.ts
- src/utils/near.ts
> feat: core functionality of withdraw

- package.json
- src/features/deposit/components/DepositForm/index.tsx
- src/features/machines/backgroundBalanceActor.ts
- src/features/machines/depositUIMachine.ts
Key changes:
- Prevent interaction with deposit form if user is not logged in
- Prevent address generation if user is not logged in
Example:
> chore(deposit): warn user to login before deposit

- src/features/deposit/components/DepositForm/index.tsx
- src/features/deposit/components/DepositUIMachineFormSyncProvider.tsx
- src/features/deposit/components/DepositWidget.tsx
- src/features/machines/backgroundBalanceActor.ts
- src/features/machines/getBalanceMachine.ts
- src/types/deposit.ts
- Enhanced network selector to support EVM wallets
> feat: integrate user network selection for managing deposit flow for non-NEAR users

- src/features/deposit/components/DepositForm/index.tsx
- src/hooks/useDepositStatusSnapshot.ts
- src/hooks/usePoABridge.ts
- src/services/poaBridgeClient/apis.ts
- src/services/poaBridgeClient/types.ts
- src/types/deposit.ts
- Implement snapshot of deposited statuses
- Add polling mechanism for new deposit settlements
Example:
> feat: add polling for successful deposit

- src/features/deposit/components/DepositUIMachineProvider.tsx
- src/features/machines/depositNearMachine.ts
- src/features/machines/depositUIMachine.ts
- src/hooks/useDepositStatusSnapshot.ts
- Switch from deprecated chainId
- Fix initial deposit snapshot and cleaning
> fix: deposit flow

- src/components/Form/FieldComboInput.tsx
- src/features/deposit/components/DepositForm/index.tsx
- src/features/deposit/components/DepositForm/styles.module.css
- src/features/machines/depositUIMachine.ts
- src/features/machines/poaBridgeInfoActor.ts
- src/features/machines/withdrawUIMachine.ts
- src/features/withdraw/components/WithdrawForm/index.tsx
- src/services/poaBridgeClient/types.ts
PR adds fetching of POA Bridge `supported_tokens` and validating against minimal withdraw amount. 
Also fixes:
- form errors being reset after any input
- recipient field being reset after amount change
- balance error message is not showing up
<details><summary>Details</summary>
<p>
</p>
</details>
> feat(withdraw): Add min withdraw amount

- src/features/machines/swapUIMachine.ts
- src/features/swap/components/SwapForm.tsx
- src/features/swap/components/SwapUIMachineProvider.tsx
- src/features/withdraw/components/WithdrawForm/index.tsx
- src/features/withdraw/components/WithdrawForm/selectors.ts
<details><summary>Screenshot</summary>
<p>
</p>
</details>
> fix: add "no liquidity" message

- src/features/withdraw/components/WithdrawForm/index.tsx
- src/features/withdraw/components/WithdrawWidget.tsx
- src/types/base.ts
- src/types/deposit.ts
- src/types/withdraw.ts
<details><summary>User selected Near connected to Near (with button)</summary>
<p>
</p>
</details> 
<details><summary>User selected Ethereum connected to Near (no button)</summary>
<p>
</p>
</details>
> feat(withdraw): add button that autofills user address

- src/features/swap/components/SwapForm.tsx
- src/features/swap/components/SwapWidget.tsx
- src/types/swap.ts
<details><summary>Screenshot</summary>
<p>
</p>
</details>
> fix(deposit): add link to deposit if no funds

- src/features/machines/publicKeyVerifierMachine.ts
The main goal of this PR is to fix issue with TS 
https://github.com/defuse-protocol/defuse-sdk/actions/runs/11862143510/job/33060916576
> Error: src/features/machines/withdrawUIMachine.ts(80,14): error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.
I found that inline actions and guards cause bloating the types. So if they moved to `setup` function then everything is fine. 
So I suggest declaring actions in `setup` every time in order to avoid accidental type issues.
> fix: move inline actions to setup

- src/config/settings.ts
- src/features/deposit/components/DepositForm/index.tsx
- src/features/machines/backgroundBalanceActor.ts
- src/features/machines/depositEstimationActor.ts
- src/features/withdraw/components/WithdrawForm/index.tsx
- src/services/depositService.ts
- src/types/base.ts
- src/types/interfaces.ts
- src/utils/adapters.ts
- src/utils/validateAddress.test.ts
- src/utils/validateAddress.ts
Some thoughts about structure. It might better to have a special folder `chains`, which could contain chain specific functions. Now chain specific logic evenly spread in SDK.
Another point is address validation. Now we have regexp verification, which might not be great, since it may miss some rules. There are libraries like https://github.com/trezor/trezor-address-validator which solve this problem, but they all have some issues (e.g. no typescript, no solana, large size, etc). We may consider creating own library, maybe by forking that library and fixing all the issues.
> feat: add Dogecoin chain support

- src/components/Form/FieldComboInput.tsx
- src/components/SelectAssets.tsx
Fixes swap input layout shift on balance change
Removing some of the hardoced max width as it should be set by SDK consumer
> fix: layout shift on swap input change

- src/features/swap/components/SwapUIMachineProvider.tsx
- src/features/swap/components/SwapWidget.tsx
- src/types/swap.ts
This allows to set an initial token in , token out in widget through passing a token object. (Similar as in tokenList)
> feat: initial token for swap widget

- src/services/nep141StorageService.ts
- src/services/withdrawService.ts
ETH on Near doesn't require storage deposit
> fix: eth to near withdraw storage_deposit error

- src/features/deposit/components/DepositForm/index.tsx
- src/features/machines/depositGenerateAddressMachine.ts
- src/features/machines/depositUIMachine.ts
<details>
<summary>Example:</summary>
</details>
> fix: generating address failed message

- package.json
- yarn.lock
> chore: remove ref sdk

- src/features/deposit/components/DepositForm/index.tsx
- src/features/deposit/components/Deposits/index.tsx
<details>
<summary>Example:</summary>
</details>
> fix: add success deposit notification

- package.json
- src/config/settings.ts
- src/constants/evm.ts
- src/features/deposit/components/DepositForm/index.tsx
- src/features/machines/backgroundBalanceActor.ts
- src/features/machines/depositEstimationActor.ts
- src/features/machines/swapIntentMachine.ts
- src/features/machines/withdrawFormReducer.ts
- src/features/machines/withdrawUIMachine.ts
- src/features/withdraw/components/WithdrawForm/index.tsx
- src/features/withdraw/components/WithdrawWidget.tsx
- src/services/depositService.ts
- src/types/base.ts
- src/types/interfaces.ts
- src/utils/adapters.ts
- src/utils/chainTxExplorer.ts
- src/utils/messageFactory.test.ts
- src/utils/messageFactory.ts
- src/utils/validateAddress.ts
- yarn.lock
<details><summary>Details</summary>
<p>
</p>
</details>
> feat: add support for XRP Ledger

- src/features/deposit/components/DepositForm/index.tsx
- src/features/deposit/components/DepositUIMachineProvider.tsx
- src/features/machines/depositSolanaMachine.ts
> fix: add error when deposit amount less than min allowed

- src/utils/format.ts
Fixes tiny usd amounts
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> fix: tiny usd amounts

- src/hooks/useTokensUsdPrices.ts
Refetch price every 20 seconds
> feat: add price refetch interval

- src/features/deposit/components/DepositForm/ActiveDeposit.tsx
- src/features/swap/components/SwapForm.tsx
- src/features/withdraw/components/WithdrawForm/index.tsx
> fix: negative usd amounts

- src/components/Block/BlockMultiBalances/index.tsx
- src/components/Form/FieldComboInput.tsx
- src/features/machines/backgroundQuoterMachine.ts
- src/features/machines/depositedBalanceMachine.ts
- src/features/machines/swapIntentMachine.ts
- src/features/machines/swapUIMachine.ts
- src/features/machines/withdrawUIMachine.ts
- src/features/swap/components/SwapForm.tsx
- src/features/swap/components/SwapUIMachineProvider.tsx
- src/features/withdraw/components/WithdrawForm/index.tsx
- src/features/withdraw/components/WithdrawForm/selectors.ts
- src/services/defuseBalanceService.ts
- src/services/poaBridgeClient/types.ts
- src/services/quoteService.test.ts
- src/services/quoteService.ts
- src/services/solverRelayHttpClient/types.ts
- src/services/withdrawService.ts
This reverts commit 464f02dbc5f6e87a49e91066a0ce749a3745c027.
> Revert "feat: revert last features (#243)"

- src/components/Form/FieldComboInput.tsx
1. Removes calc width
2. Adds gradient  separator as in Deposit and Withdraw inputs
> refactor: field combo input and add gradient separators

- .github/workflows/release.yml
- .github/workflows/test.yml
- .npmrc
- README.md
- commitlint.config.cjs
- package.json
- release.config.cjs
- yarn.lock
**Goals**
1. Block any MAJOR release
2. Push to NPM registry instead of GITHUB REGISTRY 
3. Drop version to 0.0.1 as there won't be any MAJOR release any time soon (or 1.0.0?)
> feat: change release flow

- .github/workflows/release.yml
- .github/workflows/test.yml
- .npmrc
- README.md
- commitlint.config.cjs
- package.json
- release.config.cjs
- yarn.lock
This reverts commit 37f9ce042287b9a65b59823d299120bbe2b459f9.
> Revert "feat: change release flow (#248)"

- src/features/machines/depositedBalanceMachine.ts
This PR enables the use of in-flight balances before they are settled.
<details>
<summary>Example</summary>
</details>
> chore: uses optimistic balance as balance
