src/features/machines/swapIntentMachine.ts
src/features/machines/swapUIMachine.test.ts
src/features/machines/swapUIMachine.ts

`swapIntent` machine is based on `swap` machine from swap-facade repository, but the logic is adjusted to reflect new requirements. I didn't include any test because this is first draft and most likely will be changed.

feat: add new swapIntentMachine

---

src/features/deposit/depositProcessorService.ts
src/features/deposit/index.ts
src/features/machines/depositMachine.ts

- Declares state changes for direct deposits on the NEAR network and deposits via the POA bridge (generating an address).
- Created the foundational structure for the deposit service, including the main interfaces.
Note: Unit tests are not included in this PR since the core concepts of the state machine are still under development.

feat(wip): add deposit machine

---

src/components/Form/FieldComboInput.tsx
src/features/machines/swapUIMachine.test.ts
src/features/machines/swapUIMachine.ts
src/features/swap/components/SwapForm.tsx
src/features/swap/components/SwapFormProvider.tsx
src/features/swap/components/SwapUIMachineFormSyncProvider.tsx
src/features/swap/components/SwapUIMachineProvider.tsx
src/features/swap/components/SwapWidget.tsx

The main point of PR is integrate the swap UI machine into the form.
PR:
- enables widget to use swap UI machine
- replaces previous quoting mechanism
- does small refactoring
Currently we have multiple sources of truth: `amountIn` in form, selected assets in `useState` and duplicated data in state machines. All these data live in different places (files, components); they synchronize via observing variables and executing useEffects in cascade. New providers try to address this issue of synchornization and streamline the flow of data.

refactor: Use swap UI machine

---

.gitignore
artifacts/defuse_contract_abi.json
biome.json
package.json
scripts/gen-defuse-types.sh

PR adds a bash script that runs during `yarn install` to generate TypeScript types used in `defuse-contracts`. Currently, the script uses a hardcoded JSON Schema file because the contracts repository is private, so the artifacts cannot be easily accessed. In the future, this script will be updated to fetch the JSON Schema directly from the release page of `defuse-contracts`.
<details><summary>Generated defuse-contracts-types.d.ts</summary>
<p>
```ts
/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/
/**
* NEAR Account Identifier.
*
* This is a unique, syntactically valid, human-readable account identifier on the …
```

chore: add script that generates defuse-contract-types

---

src/config/settings.ts
src/features/machines/swapIntentMachine.ts
src/features/machines/swapUIMachine.ts
src/features/swap/components/SwapForm.tsx
src/features/swap/components/SwapUIMachineProvider.tsx
src/features/swap/components/SwapWidget.tsx
src/types/quoting.ts
src/types/swap.ts
src/utils/messageFactory.test.ts
src/utils/messageFactory.ts

PR: 
- adds generation of a swap message to a machine level
- updates the signature of SwapWidget to enable singing messages of different standards
Here is an example of usage the SwapWidget (I will update FE repository eventually):
```ts
<SwapWidget
tokenList={LIST_TOKENS}
signMessage={async (params) => {
const sig = await signMessage({
...params.NEP141,
nonce: Buffer.from(params.NEP141.nonce),
})
if (!sig) {
throw new Error("No signature")
}
return { type: "NEP141", signatureData: sig }
}}
/>
```

feat(SwapWidget)!: Add swap message generation

---

src/features/machines/swapIntentMachine.ts
src/features/machines/swapUIMachine.test.ts
src/features/machines/swapUIMachine.ts
src/features/swap/components/SwapForm.tsx
src/features/swap/components/SwapUIMachineFormSyncProvider.tsx
src/features/swap/components/SwapUIMachineProvider.tsx
src/features/swap/components/SwapWidget.tsx
src/types/swap.ts

PR: 
- updates swap-ui machine to store inputs (token in/out and amount in) and pass them to swap-intent machine (very questionable change) 
- formalizes a status of the outcome of the swap-intent 
- adds `onSwapSuccess` callback

feat: add on swap success callback

---

src/components/Asset/AssetComboIcon.tsx
src/components/Asset/AssetList.tsx
src/components/Form/FieldComboInput.tsx
src/components/Modal/ModalDepositSelectAssets.tsx
src/components/Modal/ModalSelectAssets.tsx
src/components/Network/AssetList.tsx
src/components/SelectAssets.tsx
src/features/deposit/components/Form/DepositFormNear/index.tsx
src/features/machines/swapIntentMachine.ts
src/features/machines/swapUIMachine.ts
src/features/swap/components/SwapForm.tsx
src/features/swap/components/SwapUIMachineProvider.tsx
src/features/swap/components/SwapWidget.tsx
src/stores/tokensStore.ts
src/types/base.ts
src/types/swap.ts
src/utils/token.ts

PR introduces `UnifiedTokenInfo` type, which solves natively multichain assets problem. 
```ts
/**
* A virtual aggregation of the same token across multiple blockchains.
* This is not an on-chain token but a unified view of network-specific tokens
* with shared properties.
*
* The name avoids "NativeMultichainAsset" to clarify that it doesn't represent
* an actual multichain token, just a virtual abstraction.
*/
export interface UnifiedTokenInfo {
unifiedAssetId: string
symbol: string
name: string
decimals: number
icon: string
groupedTokens: BaseTokenInfo[]
}
```
<details><summary>Example of definition of USDC</summary>
<p>
```ts
{
unifiedAssetId: "usdc",
symbol: "USDC",
name: "USDC",
decimals: 6,
icon: "https://assets.coingecko.com/coins/images/6319/standard/usdc.png",
groupedTokens: [
{ …
```

feat: add unified token

---

package.json
src/features/machines/swapIntentMachine.ts
src/types/swap.ts
src/utils/__snapshots__/prepareBroadcastRequest.test.ts.snap
src/utils/messageFactory.test.ts
src/utils/messageFactory.ts
src/utils/prepareBroadcastRequest.test.ts
src/utils/prepareBroadcastRequest.ts
yarn.lock

PR:
- adds `@scure/base` package for base58 utility functions (it is already used by some of the dependencies)
- updates machines to store signature and signed message
- add transform functions that prepare data for sending to API

feat(swap): transform signature to base58

---

src/services/solverRelayHttpClient/apis.ts
src/services/solverRelayHttpClient/index.ts
src/services/solverRelayHttpClient/runtime.ts
src/services/solverRelayHttpClient/types.ts

I couldn't generate a client using JSON Schema and wrote a core implementation. It lacks of response data validation and proper JSON-RPC error propagation though. But for now as a starting point it is fine.

feat: add solver relay rpc http client

---

src/services/solverRelayHttpClient/types.ts
src/types/swap.ts
src/utils/__snapshots__/prepareBroadcastRequest.test.ts.snap
src/utils/messageFactory.test.ts
src/utils/messageFactory.ts
src/utils/prepareBroadcastRequest.test.ts
src/utils/prepareBroadcastRequest.ts

`callbackUrl` is important part of singing a message. It used to incorrect handle it. PR fix it as well as incorrect standard naming.

fix: Fix singing with `callbackUrl`

---

artifacts/defuse_contract_abi.json
src/services/solverRelayHttpClient/types.ts
src/utils/__snapshots__/prepareBroadcastRequest.test.ts.snap
src/utils/prepareBroadcastRequest.ts

After discussion with a team, we decided to get rid of flatten structure and put the payload to `payload`.

fix: update sign data structure

---

src/features/machines/queryQuoteMachine.test.ts
src/features/machines/queryQuoteMachine.ts
src/features/machines/swapUIMachine.ts
src/features/swap/components/SwapUIMachineProvider.tsx

Quoting natively multichain asset is challenging, because it depends on users actual balance. On one hand, we ought to give user a quote for any give input even if user does not have funds (e.g. user didn't connect). On other hand, we have to consider user balance, when user quotes for swap, for example, user has 1000 USDC on Solana, so it does not make sense to quote for 1000 USDC on Near, as they cannot do anything with this quote.
- add a couple of functions that solves client routing problem
- update swapUIMachine to use real quoting
(didn't update swapIntentMachine, because it won't directly use queryQuoteMachine)

feat: add real quoting via relay api

---

src/features/machines/publicKeyVerifierMachine.ts
src/features/machines/swapIntentMachine.ts
src/features/machines/swapUIMachine.ts
src/features/swap/components/SwapForm.tsx
src/features/swap/components/SwapSubmitter.tsx
src/features/swap/components/SwapWidget.tsx
src/types/swap.ts

Public key is important part of Defuse protocol. Most blockchain accounts one way or another have public keys. In most blockchains accounts have a single immutable pub key, but on Near accounts can manage their public keys (add or delete them). 
When user signs a message, they use a public key. In order to allow a particular public key to manage user's assets, user needs to tell us about that key by sending a transaction (`add_public_key` to defuse contract). 
PR adds an extra step before publishing an intent. On that step it checks presence of the public key (extracted from signature), and if not it urges the user to send a `add_public_key` transaction.

feat: verify public key after singing swap message 

---

src/features/machines/queryQuoteMachine.ts
src/features/machines/swapIntentMachine.ts
src/features/machines/swapUIMachine.ts
src/features/swap/components/SwapForm.tsx
src/features/swap/components/SwapUIMachineFormSyncProvider.tsx
src/services/intentService.ts
src/services/solverRelayHttpClient/types.ts
src/types/swap.ts

The main purpose of the PR is to formalize states of the swap flow and statuses of an intent. The main changes are made in `swapIntentMachine`. The swap flow states are grouped by intent creation outcomes:
- "sad" states (we could not create an intent)
- `ERR_USER_DIDNT_SIGN`
- `ERR_SIGNED_DIFFERENT_ACCOUNT`
- `ERR_CANNOT_VERIFY_PUBLIC_KEY`
- `ERR_CANNOT_ADD_PUBLIC_KEY`
- `ERR_CANNOT_PUBLISH_INTENT`
- "happy" states (we managed to create an intent)
- `SETTLED`
- `NOT_FOUND_OR_NOT_VALID`
- `ERR_CANNOT_OBTAIN_INTENT_STATUS`

feat: status of intent

---

src/features/machines/intentStatusMachine.ts
src/features/machines/swapIntentMachine.ts
src/features/machines/swapUIMachine.ts
src/features/swap/components/SwapForm.tsx
src/features/swap/components/SwapUIMachineFormSyncProvider.tsx
src/services/intentService.ts

This PR is follow-up of https://github.com/defuse-protocol/defuse-sdk/pull/64 
The main goal of this PR is to separate intent statuses from `swapIntentMachine`.
`swapIntentMachine` will just create an intent and return its hash. `swapUIMachine` will grab the result and create another actor which will be responsible for storing the status of the intent and poll API for a settlement status.
Such separation enables granular control over the intents, so we could render them easily concurrently.
<details><summary>Screenshot: How we can render multiple concurrent intents</summary>
<p>
</p>
</details>

refactor: separate intent

---

src/components/Form/FieldComboInput.tsx
src/components/Modal/ModalConfirmAddPubkey.tsx
src/components/Modal/ModalContainer.tsx
src/components/Modal/ModalDialog/index.tsx
src/features/machines/publicKeyVerifierMachine.ts
src/features/machines/swapIntentMachine.ts
src/features/machines/swapUIMachine.ts
src/features/swap/components/SwapForm.tsx
src/features/swap/components/SwapSubmitter.tsx
src/features/swap/components/SwapUIMachineFormSyncProvider.tsx
src/stores/modalStore.ts

We need to send a one time transaction to add Public key to Defuse protocol for users with `foo.near` handles. We send this transaction right after signing a message. Browser don't open new windows from timeouts or other random macro tasks, they allow to open windows only on user interaction (e.g. click).
PR adds new modal dialog that asks user to confirm their account, upon clicking Confirm we open a wallet window (and browser won't block this new window).
<details><summary>Details</summary>
<p>
</p>
</details>

fix: fix pub key window blocking

---

src/components/Modal/ModalDialog/index.tsx
src/features/swap/components/SwapForm.tsx

Two fixes:
- don't switch amounts when token selected from dialog
- remove focusing the first input in dialog

fix: don't switch amounts when token selected from dialog

---

src/components/Input/index.tsx
src/components/Select/Select.tsx
src/features/deposit/components/DepositForm/index.tsx
src/features/deposit/components/DepositForm/styles.module.css
src/features/deposit/components/DepositUIMachineFormSyncProvider.tsx
src/hooks/useNearGetTokenBalance.ts
src/hooks/usePoABridge.ts
src/types/deposit.ts

When the user is handling NEAR tokens, the network is already known, so there’s no need to prompt the user to select it manually; instead, selection is disabled and handled automatically.
Changes:
- Adjust the selection behavior, as the form may be modified not only by the user

chore(deposit): disable network for non muli-asset

---

src/features/deposit/components/DepositForm/index.tsx
src/features/deposit/components/Deposits/index.tsx
src/features/machines/depositNearMachine.ts
src/features/machines/depositUIMachine.ts

- Update `depositNearMachine` outputs
- Add Deposits component for rendering deposit result with `txHash`
Example:

chore: enhance success and failure handling

---

src/config/settings.ts

The defuse contract ID has been updated to a new version, which may affect existing integrations. 
Ensure to update your configurations accordingly.

feat: migrate to new version of defuse contract

---

src/features/deposit/components/DepositForm/index.tsx
src/features/deposit/components/DepositForm/styles.module.css
src/features/deposit/components/DepositUIMachineFormSyncProvider.tsx
src/features/deposit/components/DepositUIMachineProvider.tsx
src/features/deposit/components/DepositWidget.tsx
src/features/deposit/components/Deposits/index.tsx
src/features/machines/backgroundBalanceActor.ts
src/features/machines/depositEVMMachine.ts
src/features/machines/depositUIMachine.ts
src/features/machines/getBalanceMachine.ts
src/services/depositService.ts
src/types/deposit.ts

This PR enables direct deposits using an EVM-connected wallet.
- The Deposit UI machine is now responsible for routing between NEAR and EVM submissions
- A separate deposit EVM machine has been added
- The deposit balance machine can now fetch balances for ERC20 tokens or native balances using the RPC URL provided to the SDK
- The background balance machine is now responsible for fetching EVM tokens based on the network
- The deposit service has been extended with two functions needed for fetching balances

feat(deposit): allow direct deposit through evm wallet

---

src/services/depositService.ts

Due to issues reported by our users with deposits using the Phantom wallet on the Solana network, we have decided to disable it.

fix: disable deposits on solana

---

package.json
tailwind.config.js
yarn.lock

chore: remove unnecesary tailwind dependecy

---

src/config/settings.ts
src/constants/aurora.ts
src/constants/index.ts
src/features/deposit/components/DepositForm/index.tsx
src/features/deposit/components/DepositUIMachineProvider.tsx
src/features/deposit/components/DepositWidget.tsx
src/features/deposit/components/Deposits/index.tsx
src/features/machines/depositTurboMachine.ts
src/features/machines/depositUIMachine.ts
src/services/depositService.ts
src/types/deposit.ts
src/types/quoting.ts
src/utils/chainTxExplorer.ts

This update enables users to make direct deposits on Turbochain using EVM wallets such as MetaMask.
For the completion of this PR, the following updates are required:
- Add the `siloToSilo` contract to `silo.turbochain` at settings.
Example:
---

feat: enabled deposit to turbochain

---

src/components/Block/BlockMultiBalances/index.tsx
src/components/Form/FieldComboInput.tsx

Set a default padding for the Input and remove layout shif
Before
https://github.com/user-attachments/assets/cf72487d-690f-4403-a156-fbbb960cfedd
After
https://github.com/user-attachments/assets/eb041030-688b-478d-95b8-d4959d11d07c
I also think this stuff on screenshot is legacy

fix: balance block layout shift

---

package.json
src/services/intentService.ts
yarn.lock

Adding retires for intent publishing.
This library is used - https://github.com/lifeomic/attempt
It has 0 deps
Some context for params usage - https://encore.dev/blog/retries
Some example of timing I get for retries
a small code sample to try it locally
```
import { retry } from "@lifeomic/attempt"
let counter = 0
async function main() {
await retry(
async () => {
const a = new Date()
console.log(
counter,
`${a.getHours()}:${a.getMinutes()}:${a.getSeconds()}:${a.getMilliseconds()}`
)
if (counter > 123) {
return
}
counter++
throw new Error()
},
{
delay: 1000,
factor: 1.5,
maxAttempts: 7,
jitter: true,
minDelay: 1000,
}
)
}
main()
```

feat: publish intent retry

---

src/config/settings.ts

The reason for switching to another is that this RPS is unstable, 
Score | Privacy are negative at Chainlist:

chore: change eth rpc url

---

src/features/deposit/components/DepositForm/index.tsx
src/features/machines/depositUIMachine.ts

If `backgroundBalanceActor` crashes due to PRC then show an error message to the user.
<details>
<summary>Example:</summary>
</details>

fix: add warning if fetch balance is failed

---

package.json
rollup.config.js
src/features/machines/backgroundQuoterMachine.ts
src/logger.ts
src/services/quoteService.ts

PR introduces `logger` which is global configurable object. Logger lives in a separate file and treated as an entry point. It's need for better tree-shaking, so user who want to configure it don't end up loading entire library:
```js
function someGlobalInitFn() {
const {setLogger} = await import("@defuse-protocol/defuse-sdk/logger")
setLogger(...)
}
```
Logger has conventional method like error, info, etc. Also it has verbose, which will be used as a breadcrumb for an event. In follow up PR I will update all usage of console.log in the code.

feat: track No liquidity event

---

src/features/machines/getBalanceMachine.ts

Current padding is 1 NEAR which a lot for users with small balance. MNW has a padding of 0.07 but I decided to be more cautious and set it to 0.1 in case other wallets are more strict.

feat: change NEAR balance padding from 1 to 0.1

---

src/components/Block/BlockMultiBalances/index.tsx
src/components/Form/FieldComboInput.tsx
src/components/Input/index.tsx
src/features/deposit/components/DepositForm/index.tsx
src/features/swap/components/SwapForm.tsx
src/features/withdraw/components/WithdrawForm/index.tsx
src/utils/format.ts
src/utils/getTokenUsdPrice.ts

A demo for review of how I can add USD prices to input fields.
A few things left to add 
1. Formatting for really big USD amounts to avoid scientific notation in UI. Probably using Intl or some other way like 10mil 223th.
2. I ll add overall formatting to avoid a lot of digits after the decimal point.

feat: add usd prices to token fields

---

README.md

To avoid confusion with download of the package I think it is important to mention that sdk consumer need to have a npmrc file to install the package

docs: mention npmrc in readme as it is necessary for installing the sdk

---

src/features/machines/publicKeyVerifierMachine.ts
src/features/machines/swapIntentMachine.ts
src/features/machines/swapUIMachine.ts
src/features/machines/withdrawUIMachine.ts
src/features/swap/components/SwapUIMachineProvider.tsx
src/features/swap/components/SwapWidget.tsx
src/features/withdraw/components/WithdrawWidget.tsx
src/types/swap.ts
src/types/withdraw.ts
src/utils/messageFactory.test.ts
src/utils/messageFactory.ts

PR also includes small refactoring of `publicKeyVerifierMachine`, otherwise sdk couldn't compile because of bloated types:
```
src/features/machines/withdrawUIMachine.ts(83,14): error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.
```

feat: add configurable referral field
